#####
#
# DAG-GEO_TEST.yaml: example of a docker dag that processes
#  tudelft flood data
#
# Copyright 2024 Broda Group Software Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# Created:  2024-07-22 by 15205060+DavisBroda@users.noreply.github.com
#####

tasks:

  task-preprocessing:
    downstream: [geoserver-load-pipeline]

  geoserver-load-pipeline:
    type: docker
    downstream: [task-postprocessing]

  task-postprocessing:
    downstream: []
